create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique not null,onboarding_completed boolean not null default false,timezone text not null default 'Asia/Tokyo',created_at timestamptz not null default now());
create table if not exists public.habits(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,category text not null,goal_text text not null,minimum_action text not null,is_active boolean not null default true,created_at timestamptz not null default now());
create unique index if not exists one_active_habit_per_user on public.habits(user_id) where is_active;
create table if not exists public.excuse_tickets(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,habit_id uuid not null references public.habits(id) on delete cascade,excuse_text text not null,is_preset boolean not null default false,usage_count int not null default 0,last_used_at timestamptz,charge_complete_at timestamptz,created_at timestamptz not null default now(),unique(user_id,habit_id,excuse_text));
create table if not exists public.daily_records(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,habit_id uuid not null references public.habits(id) on delete cascade,record_date date not null,predicted_ticket_id uuid references public.excuse_tickets(id),predicted_excuse_text text not null,actual_ticket_id uuid references public.excuse_tickets(id),actual_excuse_text text,prediction_matched boolean,result_type text check(result_type in('minimum','some','full','rest','none')),action_score numeric(3,2),is_shared boolean not null default false,recorded_next_day boolean not null default false,created_at timestamptz not null default now(),result_recorded_at timestamptz,unique(user_id,record_date));
create table if not exists public.public_posts(id uuid primary key default gen_random_uuid(),daily_record_id uuid unique not null references public.daily_records(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,category text not null,excuse_text text not null,is_visible boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.reactions(id uuid primary key default gen_random_uuid(),post_id uuid not null references public.public_posts(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,reaction_type text not null check(reaction_type in('relate','idea')),created_at timestamptz not null default now(),unique(post_id,user_id,reaction_type));
create table if not exists public.event_logs(id bigint generated always as identity primary key,user_id uuid references auth.users(id) on delete set null,event_name text not null,record_date date,payload jsonb not null default '{}',created_at timestamptz not null default now());

alter table public.profiles enable row level security;alter table public.habits enable row level security;alter table public.excuse_tickets enable row level security;alter table public.daily_records enable row level security;alter table public.public_posts enable row level security;alter table public.reactions enable row level security;alter table public.event_logs enable row level security;
create policy profiles_self on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
create policy habits_self on public.habits for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy tickets_self on public.excuse_tickets for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy records_self on public.daily_records for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy public_posts_read on public.public_posts for select to authenticated using(is_visible=true);
create policy public_posts_self_insert on public.public_posts for insert to authenticated with check(auth.uid()=user_id);
create policy reactions_read on public.reactions for select to authenticated using(true);
create policy reactions_self on public.reactions for insert to authenticated with check(auth.uid()=user_id);
create policy events_self_insert on public.event_logs for insert to authenticated with check(auth.uid()=user_id);

create or replace function public.create_daily_prediction(p_habit_id uuid,p_ticket_id uuid,p_share boolean default false) returns uuid language plpgsql security definer set search_path=public as $$
declare t public.excuse_tickets;h public.habits;r uuid;d date;
begin select * into h from habits where id=p_habit_id and user_id=auth.uid();if h.id is null then raise exception 'habit not found';end if;select * into t from excuse_tickets where id=p_ticket_id and user_id=auth.uid();if t.id is null then raise exception 'ticket not found';end if;if t.charge_complete_at is not null and t.charge_complete_at>now() then raise exception 'ticket is charging';end if;d=(now() at time zone coalesce((select timezone from profiles where id=auth.uid()),'Asia/Tokyo'))::date;insert into daily_records(user_id,habit_id,record_date,predicted_ticket_id,predicted_excuse_text,is_shared) values(auth.uid(),h.id,d,t.id,t.excuse_text,p_share) returning id into r;update excuse_tickets set usage_count=usage_count+1,last_used_at=now(),charge_complete_at=date_trunc('day',now())+interval '4 days' where id=t.id;if p_share then insert into public_posts(daily_record_id,user_id,category,excuse_text) values(r,auth.uid(),h.category,t.excuse_text);end if;insert into event_logs(user_id,event_name,record_date,payload) values(auth.uid(),'daily_prediction_created',d,jsonb_build_object('ticket_id',t.id));return r;end$$;
create or replace function public.record_daily_result(p_record_id uuid,p_result_type text,p_action_score numeric,p_actual_ticket_id uuid default null,p_prediction_matched boolean default null) returns void language plpgsql security definer set search_path=public as $$
declare r public.daily_records;t public.excuse_tickets;
begin select * into r from daily_records where id=p_record_id and user_id=auth.uid();if r.id is null then raise exception 'record not found';end if;if p_actual_ticket_id is not null then select * into t from excuse_tickets where id=p_actual_ticket_id and user_id=auth.uid();if t.id is null then raise exception 'ticket not found';end if;if p_prediction_matched=false and t.id<>r.predicted_ticket_id then update excuse_tickets set usage_count=usage_count+1,last_used_at=now(),charge_complete_at=date_trunc('day',now())+interval '4 days' where id=t.id;end if;end if;update daily_records set result_type=p_result_type,action_score=p_action_score,actual_ticket_id=p_actual_ticket_id,actual_excuse_text=t.excuse_text,prediction_matched=p_prediction_matched,recorded_next_day=(record_date<current_date),result_recorded_at=now() where id=r.id;insert into event_logs(user_id,event_name,record_date,payload) values(auth.uid(),'result_recorded',r.record_date,jsonb_build_object('result',p_result_type,'matched',p_prediction_matched));end$$;
grant execute on function public.create_daily_prediction(uuid,uuid,boolean) to authenticated;grant execute on function public.record_daily_result(uuid,text,numeric,uuid,boolean) to authenticated;
create or replace view public.public_excuse_feed as select p.id,p.category,p.excuse_text,p.created_at,count(r.id) filter(where r.reaction_type='relate') as relate_count,count(r.id) filter(where r.reaction_type='idea') as idea_count from public.public_posts p left join public.reactions r on r.post_id=p.id where p.is_visible=true group by p.id,p.category,p.excuse_text,p.created_at;
grant select on public.public_excuse_feed to authenticated;
create or replace view public.research_export as select encode(digest(dr.user_id::text,'sha256'),'hex') as anonymous_id,dr.record_date,h.category,h.minimum_action,dr.predicted_excuse_text,dr.result_type,dr.action_score,dr.prediction_matched,dr.actual_excuse_text,dr.recorded_next_day,dr.created_at,dr.result_recorded_at from public.daily_records dr join public.habits h on h.id=dr.habit_id;
